import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Providers } from './providers';
import React from 'react';
import Mnnavbar from '@/components/navbar/mnnavbar';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: '计算机学院',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='zh'>
      <body className={inter.className}>
        <Mnnavbar />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
